# Generated by Django 5.1.2 on 2024-10-31 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_analisis', models.DateTimeField(auto_now=True)),
                ('jumlah_urgen', models.IntegerField(blank=True, null=True)),
                ('jumlah_laporan', models.IntegerField(blank=True, null=True)),
                ('jenis_infrastruktur', models.CharField(blank=True, choices=[('jalan', 'Jalan'), ('lampu_jalan', 'Lampu Jalan'), ('jembatan', 'Jembatan')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'analisis',
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_pengguna', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pengguna',
            },
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.AutoField(primary_key=True, serialize=False)),
                ('gambar', models.BinaryField(blank=True, null=True)),
                ('jenis', models.CharField(blank=True, choices=[('jalan', 'Jalan'), ('lampu_jalan', 'Lampu Jalan'), ('jembatan', 'Jembatan')], max_length=20, null=True)),
                ('judul', models.CharField(blank=True, max_length=20, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=100, null=True)),
                ('persentase', models.FloatField(blank=True, null=True)),
                ('cuaca', models.CharField(blank=True, choices=[('hujan', 'Hujan'), ('cerah', 'Cerah')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('selesai', 'Selesai'), ('draf', 'Draf')], max_length=20)),
                ('tgl_lapor', models.DateTimeField(auto_now=True)),
                ('tingkat_urgent', models.IntegerField(blank=True, null=True)),
                ('id_pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balap_in.pengguna')),
            ],
            options={
                'db_table': 'laporan',
            },
        ),
        migrations.CreateModel(
            name='Peta',
            fields=[
                ('id_peta', models.AutoField(primary_key=True, serialize=False)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('jalan', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('id_laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balap_in.laporan')),
            ],
            options={
                'db_table': 'peta',
            },
        ),
        migrations.AddField(
            model_name='laporan',
            name='id_peta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balap_in.peta'),
        ),
        migrations.CreateModel(
            name='Rekomendasi',
            fields=[
                ('id_rekomendasi', models.AutoField(primary_key=True, serialize=False)),
                ('status_urgent', models.CharField(blank=True, choices=[('tinggi', 'Tinggi'), ('sedang', 'Sedang'), ('rendah', 'Rendah'), ('belum', 'Belum')], max_length=10, null=True)),
                ('jumlah_laporan', models.IntegerField()),
                ('id_laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balap_in.laporan')),
                ('id_peta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balap_in.peta')),
            ],
            options={
                'db_table': 'rekomendasi',
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id_notifikasi', models.AutoField(primary_key=True, serialize=False)),
                ('pesan', models.CharField(max_length=255)),
                ('tgl_notif', models.DateTimeField(auto_now=True)),
                ('id_analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balap_in.analisis')),
                ('id_rekomendasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balap_in.rekomendasi')),
            ],
            options={
                'db_table': 'notifikasi',
            },
        ),
        migrations.AddField(
            model_name='analisis',
            name='id_rekomendasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balap_in.rekomendasi'),
        ),
    ]
