# Generated by Django 5.1.2 on 2025-01-01 09:27

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balap_in', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisis',
            name='id_rekomendasi',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='id_analisis',
        ),
        migrations.RenameField(
            model_name='laporan',
            old_name='tingkat_urgent',
            new_name='cluster',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='nama',
        ),
        migrations.AddField(
            model_name='pengguna',
            name='tgl_pengguna',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 9, 26, 29, 955274)),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AddField(
            model_name='rekomendasi',
            name='tingkat_urgent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='cuaca',
            field=models.CharField(blank=True, choices=[('hujan', 'Hujan'), ('cerah', 'Cerah')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='id_pengguna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balap_in.pengguna'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='id_peta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peta', to='balap_in.peta'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='jenis',
            field=models.CharField(blank=True, choices=[('jalan', 'Jalan'), ('lampu_jalan', 'Lampu Jalan'), ('jembatan', 'Jembatan')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='judul',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(blank=True, choices=[('selesai', 'Selesai'), ('ditangani', 'Ditangani')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='tgl_lapor',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 9, 26, 29, 955274)),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='tgl_notif',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 9, 26, 29, 955274)),
        ),
        migrations.AlterField(
            model_name='peta',
            name='id_laporan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='balap_in.laporan'),
        ),
        migrations.AlterField(
            model_name='rekomendasi',
            name='status_urgent',
            field=models.CharField(blank=True, choices=[('tinggi', 'Tinggi'), ('sedang', 'Sedang'), ('rendah', 'Rendah')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='rekomendasi',
            constraint=models.UniqueConstraint(fields=('id_laporan_id', 'id_peta_id'), name='unique_laporan_peta'),
        ),
        migrations.DeleteModel(
            name='Analisis',
        ),
    ]
